<?php

require_once __DIR__ . "/utils/links.php";

/**
 * Configuration constant mapping breadcrumb keys to their corresponding URLs.
 *
 * This array defines the navigation paths for the breadcrumb system.
 * Key: The unique identifier for the page.
 * Value: The absolute URL path generated by the createLink function.
 */
define("BREADCRUMB_MAP", [
    'Home' => createLink("/index.php"),
    'Event' => createLink("/event.php"),
    'Admin' => createLink("/admin/index.php"),
    'Admin-users' => createLink("/admin/users.php"),
    'Admin-events' => createLink("/admin/events.php"),
    'Admin-users-update' => createLink("/admin/user.php"),
    'Admin-events-update' => createLink("/admin/events/update.php"),
]);

/**
 * Configuration constant mapping breadcrumb keys to their display labels.
 *
 * This array defines the human-readable text shown in the navigation UI.
 * Key: The unique identifier for the page (matching BREADCRUMB_MAP).
 * Value: The localized (Czech) label string.
 */
define("BREADCRUMB_ALIASES", [
    'Home' => "Domů",
    'Event' => "Událost",
    'Admin' => "Admin",
    'Admin-users' => "Uživetelé",
    'Admin-events' => "Události",
    'Admin-users-update' => "Úprava",
    'Admin-events-update' => "Událost",
]);

/**
 * Generates the HTML for the breadcrumb navigation based on a list of keys.
 *
 * This function takes an array of location keys, verifies them against the
 * global configuration maps, and constructs an HTML unordered list.
 * The final item in the list is rendered as plain text (indicating the current page),
 * while all preceding items are rendered as clickable links.
 *
 * @param string[] $items An ordered array of breadcrumb keys (e.g., ['Home', 'Admin']).
 * @return string The generated HTML markup for the breadcrumb navigation.
 */
function generateBreadcrumbs(array $items): string {
    $validItems = [];

    foreach ($items as $item) {
        if (array_key_exists($item, BREADCRUMB_MAP)) {
            $validItems[] = $item;
        }
    }

    if (empty($validItems)) {
        return '';
    }

    $html = '<ul class="breadcrumb">';
    $count = count($validItems);
    $currentIndex = 0;

    foreach ($validItems as $key) {
        $currentIndex++;
        $url = BREADCRUMB_MAP[$key];

        $safeLabel = htmlspecialchars(BREADCRUMB_ALIASES[$key]);

        if ($currentIndex === $count) {
            $html .= "<li>$safeLabel</li>";
        } else {
            $html .= "<li><a href=\"$url\">$safeLabel</a></li>";
        }
    }

    $html .= '</ul>';

    $html = '<div class="breadcrumb-container">' . $html . '</div>';

    return $html;
}